[build]
  publish = "public"

[build.environment]
  NODE_VERSION = "14.12.0"
  YARN_VERSION = "1.22.5"

[[redirects]]
  from = "https://riebesell.netlify.com/*"
  to = "https://riebesell.science/:splat"
  force = true
